/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentación;

import colecciones.Figuras;

/**
 *
 * @author nina.valdivia
 */
public class FrmFiguras extends javax.swing.JFrame {
    private Figuras miColeccion;
    /**
     * Creates new form FrmFiguras
     */
    public FrmFiguras() {
        initComponents();
        this.setSize(800,500);
        this.setLocationRelativeTo(null);
        miColeccion= new Figuras("figuras.txt");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnMostraColección = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtColección = new javax.swing.JTextArea();
        btnMostrarAreas = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreas = new javax.swing.JTextArea();
        btnPerimetroPrimerCirculo = new javax.swing.JButton();
        lblPerimetro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Colección de Figuras");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 390, 40);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        btnMostraColección.setText("Ver Colección");
        btnMostraColección.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostraColecciónActionPerformed(evt);
            }
        });
        jPanel1.add(btnMostraColección);
        btnMostraColección.setBounds(10, 10, 160, 23);

        txtColección.setColumns(10);
        txtColección.setRows(5);
        jScrollPane1.setViewportView(txtColección);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 40, 160, 230);

        btnMostrarAreas.setText("Ver Áreas");
        btnMostrarAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarAreasActionPerformed(evt);
            }
        });
        jPanel1.add(btnMostrarAreas);
        btnMostrarAreas.setBounds(190, 10, 200, 23);

        txtAreas.setColumns(15);
        txtAreas.setRows(5);
        jScrollPane2.setViewportView(txtAreas);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(190, 40, 200, 230);

        btnPerimetroPrimerCirculo.setText("Perímetro 1er Círculo");
        btnPerimetroPrimerCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroPrimerCirculoActionPerformed(evt);
            }
        });
        jPanel1.add(btnPerimetroPrimerCirculo);
        btnPerimetroPrimerCirculo.setBounds(410, 10, 150, 23);

        lblPerimetro.setBackground(new java.awt.Color(204, 255, 204));
        lblPerimetro.setOpaque(true);
        jPanel1.add(lblPerimetro);
        lblPerimetro.setBounds(410, 50, 150, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 60, 680, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostraColecciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostraColecciónActionPerformed
        // TODO add your handling code here:
        this.txtColección.setText(miColeccion.toString());
       
        
    }//GEN-LAST:event_btnMostraColecciónActionPerformed

    private void btnMostrarAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarAreasActionPerformed
        // TODO add your handling code here:
        this.txtAreas.setText(miColeccion.mostrarAreas());
        
    }//GEN-LAST:event_btnMostrarAreasActionPerformed

    private void btnPerimetroPrimerCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroPrimerCirculoActionPerformed
        // TODO add your handling code here:
        this.lblPerimetro.setText(miColeccion.getPerimetroPrimerCirculo()+"");
    }//GEN-LAST:event_btnPerimetroPrimerCirculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFiguras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostraColección;
    private javax.swing.JButton btnMostrarAreas;
    private javax.swing.JButton btnPerimetroPrimerCirculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPerimetro;
    private javax.swing.JTextArea txtAreas;
    private javax.swing.JTextArea txtColección;
    // End of variables declaration//GEN-END:variables
}
